In [3]:
import pandas as pd

In [25]:
pop2009 = pd.read_csv("POP2009.csv")
pop2009.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             53 non-null     object
 1   popestimate2009  53 non-null     int64
dtypes: int64(1), object(1)
memory usage: 980.0+ bytes

In [30]:
columns_to_keep1 = ["name", "popestimate2009"]
pop2009 = pop2009[columns_to_keep1]

# Define a dictionary to map old column names to new ones
column_renamed = {
    'NAME': 'name',
    'POPESTIMATE2009 ' : 'popestimate2009',
}

# Rename the columns using the mapping
pop2009.rename(columns=column_renamed, inplace=True)

# Save the DataFrame with the new column names to a new CSV file
pop2009.to_csv('POP2009.csv', index=False)

pop2009.info()

KeyError: "['name'] not in index"

In [11]:
pop2020 = pd.read_csv("POP2010-2020.csv")
pop2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SUMLEV             57 non-null     int64
 1   REGION             57 non-null     object
 2   DIVISION           57 non-null     object
 3   STATE              57 non-null     int64
 4   NAME               57 non-null     object
 5   CENSUS2010POP      57 non-null     int64
 6   ESTIMATESBASE2010  57 non-null     int64
 7   POPESTIMATE2010    57 non-null     int64
 8   POPESTIMATE2011    57 non-null     int64
 9   POPESTIMATE2012    57 non-null     int64
 10  POPESTIMATE2013    57 non-null     int64
 11  POPESTIMATE2014    57 non-null     int64
 12  POPESTIMATE2015    57 non-null     int64
 13  POPESTIMATE2016    57 non-null     int64
 14  POPESTIMATE2017    57 non-null     int64
 15  POPESTIMATE2018    57 non-null     int64
 16  POPESTIMATE2019    57 non-null     int64
 17  POPESTIMATE042020  57 non-null     int64
 18  POPESTIMATE2020    57 non-null     int64
dtypes: int64(16), object(3)
memory usage: 8.6+ KB

In [12]:
# Assuming nuforc is a Pandas DataFrame
columns_to_delete = ["SUMLEV", "REGION", "DIVISION", "STATE", "CENSUS2010POP", "ESTIMATESBASE2010", "POPESTIMATE042020", "POPESTIMATE2020" ]
pop2020 = pop2020.drop(columns=columns_to_delete)
pop2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             57 non-null     object
 1   POPESTIMATE2010  57 non-null     int64
 2   POPESTIMATE2011  57 non-null     int64
 3   POPESTIMATE2012  57 non-null     int64
 4   POPESTIMATE2013  57 non-null     int64
 5   POPESTIMATE2014  57 non-null     int64
 6   POPESTIMATE2015  57 non-null     int64
 7   POPESTIMATE2016  57 non-null     int64
 8   POPESTIMATE2017  57 non-null     int64
 9   POPESTIMATE2018  57 non-null     int64
 10  POPESTIMATE2019  57 non-null     int64
dtypes: int64(10), object(1)
memory usage: 5.0+ KB

In [18]:
pop2022 = pd.read_csv("POP2020-2022.csv")
pop2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 45 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SUMLEV                 66 non-null     int64
 1   REGION                 66 non-null     object
 2   DIVISION               66 non-null     object
 3   STATE                  66 non-null     int64
 4   NAME                   66 non-null     object
 5   ESTIMATESBASE2020      66 non-null     int64
 6   POPESTIMATE2020        66 non-null     int64
 7   POPESTIMATE2021        66 non-null     int64
 8   POPESTIMATE2022        66 non-null     int64
 9   NPOPCHG_2020           66 non-null     int64
 10  NPOPCHG_2021           66 non-null     int64
 11  NPOPCHG_2022           66 non-null     int64
 12  BIRTHS2020             66 non-null     int64
 13  BIRTHS2021             66 non-null     int64
 14  BIRTHS2022             66 non-null     int64
 15  DEATHS2020             66 non-null     int64
 16  DEATHS2021             66 non-null     int64
 17  DEATHS2022             66 non-null     int64
 18  NATURALCHG2020         66 non-null     int64
 19  NATURALCHG2021         66 non-null     int64
 20  NATURALCHG2022         66 non-null     int64
 21  INTERNATIONALMIG2020   66 non-null     int64
 22  INTERNATIONALMIG2021   66 non-null     int64
 23  INTERNATIONALMIG2022   66 non-null     int64
 24  DOMESTICMIG2020        66 non-null     int64
 25  DOMESTICMIG2021        66 non-null     int64
 26  DOMESTICMIG2022        66 non-null     int64
 27  NETMIG2020             66 non-null     int64
 28  NETMIG2021             66 non-null     int64
 29  NETMIG2022             66 non-null     int64
 30  RESIDUAL2020           66 non-null     int64
 31  RESIDUAL2021           66 non-null     int64
 32  RESIDUAL2022           66 non-null     int64
 33  RBIRTH2021             66 non-null     float64
 34  RBIRTH2022             66 non-null     float64
 35  RDEATH2021             66 non-null     float64
 36  RDEATH2022             66 non-null     float64
 37  RNATURALCHG2021        66 non-null     float64
 38  RNATURALCHG2022        66 non-null     float64
 39  RINTERNATIONALMIG2021  66 non-null     float64
 40  RINTERNATIONALMIG2022  66 non-null     float64
 41  RDOMESTICMIG2021       66 non-null     float64
 42  RDOMESTICMIG2022       66 non-null     float64
 43  RNETMIG2021            66 non-null     float64
 44  RNETMIG2022            66 non-null     float64
dtypes: float64(12), int64(30), object(3)
memory usage: 23.3+ KB

In [19]:
# Too many columns to delete, choosing a function that keeps certain columns instead
columns_to_keep2 = ["NAME", "POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022"]
pop2022 = pop2022[columns_to_keep2]
pop2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             66 non-null     object
 1   POPESTIMATE2020  66 non-null     int64
 2   POPESTIMATE2021  66 non-null     int64
 3   POPESTIMATE2022  66 non-null     int64
dtypes: int64(3), object(1)
memory usage: 2.2+ KB

In [ ]:
merged_pop = pd.merge(pop2009, pop2020, on="NAME")

In [ ]:

data_path = "state_counts.csv"
ufo_data_path = "../nuforc_reports.csv"
population_data_path = ""

df = pd.read_csv(data_path)
shape = gpd.read_file(shape_path)
udf = pd.read_csv(ufo_data_path)

#Remove unnesecary columns
udf = udf.drop(columns=["summary", "country", "date_time", "shape", "duration"])

# Aggregate data

state_counts = udf['state'].value_counts()
city_counts = udf['city'].value_counts()


state_counts_df = pd.DataFrame({'state': state_counts.index, 
                                'stateCount': state_counts.values, 
                                'city': city_counts.index,
                                'cityCount' : city_counts.values,
                                'latitude':udf['city_latitude'], 
                                'longtitude': udf['city_longtitude']})

state_counts_file = 'counts.csv'
state_counts_df.to_csv(state_counts_file, index=False)



# Mapping of state abbreviations to full names
state_abbreviations = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia',
    'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',
    'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts',
    'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
    'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico',
    'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont',
    'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming'
}


# Clean and transform the 'state' column
df['state'] = df['state'].str.upper().str.strip().map(state_abbreviations)
df.dropna(subset=['state'], inplace=True)  # Drop rows with NaN values

# List of American state names
american_states = set(state_abbreviations.values())

# Filter the DataFrame to include only American states
df = df[df['state'].isin(american_states)]

# Group by 'state' and sum the 'count' values
df = df.groupby('state', as_index=False)['count'].sum()

,NAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE042020,POPESTIMATE2020
0,United States,309327143,311583481,313877662,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329398742,329484123
1,Northeast Region,55380764,55608318,55782661,55912775,56021339,56052790,56063777,56083383,56084543,56002934,55924275,55849869
2,Midwest Region,66975328,67164092,67348275,67576524,67765576,67885682,68018175,68160342,68263019,68340091,68357895,68316744
3,South Region,114869421,116019483,117264196,118397213,119666248,121049223,122419547,123611036,124649156,125686544,126494232,126662754
4,West Region,72101630,72791588,73482530,74173435,74933166,75751299,76570256,77267367,77841481,78300384,78622340,78654756
5,Alabama,4785514,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4920706,4921532
6,Alaska,713982,722349,730810,737626,737075,738430,742575,740983,736624,733603,732074,731158
7,Arizona,6407342,6473416,6556344,6634690,6732873,6832810,6944767,7048088,7164228,7291843,7393900,7421401
8,Arkansas,2921998,2941038,2952876,2960459,2968759,2979732,2991815,3003855,3012161,3020985,3029672,3030522
9,California,37319550,37636311,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39418894,39368078
10,Colorado,5047539,5121900,5193660,5270774,5352637,5454328,5543844,5617421,5697155,5758486,5798266,5807719
11,Connecticut,3579173,3588632,3595211,3595792,3595697,3588561,3579830,3575324,3574561,3566022,3561494,3557006
12,Delaware,899647,907590,915518,924062,933131,942065,949989,957942,966985,976668,984899,986809
13,District of Columbia,605282,620290,635737,651559,663603,677014,687576,697079,704147,708253,712185,712816
14,Florida,18846143,19055607,19302016,19551678,19853880,20219111,20627237,20977089,21254926,21492056,21688239,21733312
15,Georgia,9712209,9803630,9903580,9975592,10071204,10183353,10308442,10417031,10519389,10628020,10695662,10710017
16,Hawaii,1364004,1379562,1395199,1408822,1415335,1422999,1428885,1425763,1423102,1415615,1410587,1407006
17,Idaho,1570819,1584272,1595910,1612053,1632248,1652495,1684036,1719745,1752074,1789060,1818238,1826913
18,Illinois,12840545,12867783,12883029,12895778,12885092,12859585,12821709,12779893,12724685,12667017,12615162,12587530
19,Indiana,6490555,6517250,6538989,6570575,6596019,6611442,6637898,6662068,6698481,6731010,6752183,6754953
20,Iowa,3050819,3066772,3076844,3093935,3110643,3122541,3133210,3143734,3149900,3159596,3164115,3163561
21,Kansas,2858266,2869677,2886024,2894306,2901861,2910717,2912977,2910892,2912748,2912635,2915024,2913805
22,Kentucky,4348464,4370817,4387865,4406906,4416992,4429126,4440306,4455590,4464273,4472345,4477899,4477251
23,Louisiana,4544635,4576244,4602067,4626040,4645938,4666998,4681346,4673673,4664450,4658285,4650984,4645318
24,Maine,1327651,1328473,1328094,1328543,1331217,1329098,1332348,1335743,1340123,1345770,1349647,1350141
25,Maryland,5788784,5840241,5888375,5925197,5960064,5988528,6007014,6028186,6042153,6054954,6059529,6055802
26,Massachusetts,6566440,6614218,6664269,6715158,6764864,6797484,6827280,6863560,6885720,6894883,6898116,6893574
27,Michigan,9877597,9883053,9898289,9914802,9932033,9934483,9954117,9976752,9987286,9984795,9976330,9966555
28,Minnesota,5310934,5346620,5377500,5414722,5452665,5484002,5525360,5569283,5608762,5640053,5655855,5657342
29,Mississippi,2970615,2979147,2984599,2989839,2991892,2990231,2990595,2990674,2982879,2978227,2971253,2966786
30,Missouri,5996089,6011182,6026027,6042989,6059130,6075411,6091384,6111382,6125986,6140475,6151737,6151548
31,Montana,990730,997518,1004168,1014158,1022657,1031495,1042137,1053862,1061818,1070123,1078405,1080577
32,Nebraska,1829591,1840914,1853691,1865813,1879955,1892059,1906483,1916998,1925512,1932571,1937258,1937552
33,Nevada,2702483,2713114,2744670,2776956,2818935,2868531,2919555,2972097,3030725,3090771,3128500,3138259
34,New Hampshire,1316807,1320444,1324677,1327272,1334257,1337480,1343694,1350395,1355064,1360783,1365533,1366275
35,New Jersey,8799451,8828552,8845671,8857821,8867277,8870312,8873584,8888147,8891730,8891258,8890883,8882371
36,New Mexico,2064614,2080707,2087715,2092833,2090236,2090071,2092555,2092844,2093754,2099634,2106117,2106319
37,New York,19399956,19499921,19574362,19626488,19653431,19657321,19636391,19593849,19544098,19463131,19382373,19336776
38,North Carolina,9574586,9658913,9751810,9846717,9937295,10037218,10161802,10275758,10391358,10501384,10581885,10600823
39,North Dakota,674752,685526,702227,723149,738736,755537,756114,756755,760062,763724,765224,765309
40,Ohio,11539449,11545735,11550971,11579692,11606573,11622315,11640060,11665706,11680892,11696507,11699855,11693217
41,Oklahoma,3760014,3788824,3819320,3853891,3879187,3910518,3928143,3933602,3943488,3960676,3977682,3980783
42,Oregon,3837614,3872672,3900102,3924110,3965447,4018542,4093271,4147294,4183538,4216116,4237408,4241507
43,Pennsylvania,12711406,12747052,12769123,12779538,12792392,12789838,12788468,12794679,12809107,12798883,12794404,12783254
44,Rhode Island,1053994,1053829,1054893,1055560,1056511,1056886,1057816,1056554,1059338,1058158,1058004,1057125
45,South Carolina,4635846,4672655,4719027,4766469,4826858,4896006,4963031,5027102,5091702,5157702,5205864,5218040
46,South Dakota,816193,823740,833859,842751,849670,854663,863693,873732,879386,887127,891688,892717
47,Tennessee,6355518,6400298,6455752,6496943,6544617,6595354,6651277,6714748,6778180,6830325,6875939,6886834
48,Texas,25241897,25645504,26084120,26479646,26963092,27468531,27914064,28291024,28624564,28986794,29286467,29360759
49,Utah,2775413,2814797,2854146,2898773,2938327,2983626,3044241,3103540,3155153,3203383,3239542,3249879
50,Vermont,625886,627197,626361,626603,625693,625810,624366,625132,624802,624046,623821,623347
51,Virginia,8024004,8102437,8187456,8255861,8315430,8367303,8417651,8471011,8510920,8556642,8587217,8590563
52,Washington,6743009,6827479,6898599,6966252,7057531,7167287,7299961,7427951,7526793,7614024,7678379,7693612
53,West Virginia,1854265,1856606,1857446,1854768,1850569,1843332,1832435,1818683,1805953,1795263,1788150,1784787
54,Wisconsin,5690538,5705840,5720825,5738012,5753199,5762927,5775170,5793147,5809319,5824581,5833464,5832655
55,Wyoming,564531,567491,576656,582620,583159,586389,585243,579994,579054,580116,582030,582328
56,Puerto Rico,3721525,3678732,3634488,3593077,3534874,3473232,3406672,3325284,3193344,3193553,3167851,3159343